// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBDTBucbk8Ghv-M_6qhDyweXf7rushqBnw',
    appId: '1:1061865284465:web:0b406963f8d02f4be68cd0',
    messagingSenderId: '1061865284465',
    projectId: 'sharpface',
    authDomain: 'sharpface.firebaseapp.com',
    storageBucket: 'sharpface.firebasestorage.app',
    measurementId: 'G-RC3QBGCW64',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC0-aPNzeNriy8t-Sn58XE_Ormgvp0btc4',
    appId: '1:1061865284465:android:21e4e3fe9be62031e68cd0',
    messagingSenderId: '1061865284465',
    projectId: 'sharpface',
    storageBucket: 'sharpface.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyArs6Wue-swha2KGxVWy6tFpvunX7RoNQk',
    appId: '1:1061865284465:ios:df14004f881aced6e68cd0',
    messagingSenderId: '1061865284465',
    projectId: 'sharpface',
    storageBucket: 'sharpface.firebasestorage.app',
    iosBundleId: 'com.example.sharpface',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyArs6Wue-swha2KGxVWy6tFpvunX7RoNQk',
    appId: '1:1061865284465:ios:df14004f881aced6e68cd0',
    messagingSenderId: '1061865284465',
    projectId: 'sharpface',
    storageBucket: 'sharpface.firebasestorage.app',
    iosBundleId: 'com.example.sharpface',
  );
}
